### ISSUE TITLE
NFC-1 Hardware Integration - NFC Functionality

### ISSUE THREAD

**Issue by croumeliotis** [colinbarber/COEN-ELEC-390#17]
As a game master and player, I would like to obtain the information associated with a NFC tag by scanning it with the phone
Story Points: 2
***
Scanning the NFC will capture a unique string which can be used to associate hints in game creation mode and gameplay mode
***
1) Does the app register the NFC tag when it is scanned?
2) Does the game creation activity enter hint input mode
3) Does the gameplay mode show the hint when NFC tag is scanned?
***
Tasks:
- [x] [` Determine NFC tags to purchase `](https://github.com/colinbarber/COEN-ELEC-390/issues/31)
- [x] [` Purchase NFC tags `](https://github.com/colinbarber/COEN-ELEC-390/issues/32)
- [x] [` Write NFC detection service `](https://github.com/colinbarber/COEN-ELEC-390/issues/33)
