### ISSUE TITLE
BK-6 Web Server Communication

### ISSUE THREAD

**Issue by croumeliotis** [colinbarber/COEN-ELEC-390#18]
As a game master and player, I would like to store and retrieve scavenger hunt games on the web server by using a code
Story Points: 4
***
Web server should store a file containing all the NFC tag IDs and hints 
***
1) Can the app store the data in game creation mode?
2) Can the app retrieve the data in gameplay mode?
***
Tasks:
- [x] [` Research communication environment `](https://github.com/colinbarber/COEN-ELEC-390/issues/35)
- [x] [` Implement web service `](https://github.com/colinbarber/COEN-ELEC-390/issues/36)
- [x] [` Deploy communication API `](https://github.com/colinbarber/COEN-ELEC-390/issues/37)
- [x] [` Create sample database `](https://github.com/colinbarber/COEN-ELEC-390/issues/38)
